[package]
name = "net-lattice"
version = "0.4.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
description = "A modern, cross-platform Rust library for configuring and inspecting operating system networking through a single, strongly typed API."

[dependencies]
net-lattice-core = { workspace = true }
net-lattice-ip = { workspace = true }
net-lattice-model = { workspace = true }
net-lattice-platform = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
net-lattice-backend-linux = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
net-lattice-backend-windows = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
net-lattice-backend-darwin = { workspace = true }
